- name: Install cowsay
  hosts: all
  tasks:
    - name: Install RPM
      yum:
        name: cowsay
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Install DEB
      apt: 
        name: cowsay
        state: present
      when: ansible_os_family == 'Debian'
      
    - name: Test cowsay
      shell: echo '{{ cowsay_greeting }}' | cowsay
      changed_when: False

    - name: Set Cowsay fact
      set_fact:
        cowsay_is_great: true
