- name: Install cowsay
  hosts: all
  tasks:
    - name: Install RPM
      yum:
        name: cowsay
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Install DEB
      apt: 
        name: cowsay
        state: present
      when: ansible_os_family == 'Debian'

    - name: Add cronjob
      crontab:
         name: '{{ ansible_pull_cron_name }}'
         special_time: '{{ ansible_pull_cron_time }}'
         job: ansible-pull -U  {{ ansible_pull_repo }}
         state: present
